export const AegisConfig = {
  VERSION: '1.0.0-GOD-MODE',
  ALERT_PRIORITY: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  PROXIMITY: {
    SCAN_RADIUS_METERS: 100,
    CRITICAL_RADIUS_METERS: 5,
    SCAN_INTERVAL_MS: 3000
  },
  
  CORRELATION: {
    MIN_CONFIDENCE_SCORE: 0.75,
    AUTO_ALERT_ON_FOE: true,
    SATELLITE_SYNC_ENABLED: true
  }
};
