export const EternalConfig = {
  VERSION: '1.0.0-SENTIENT-LEGACY',
  LEARNING_RATE: 0.15,
  INGESTION_CHANNELS: ['GLOBAL_NEWS', 'TECH_BREAKTHROUGHS', 'BIO_ADVANCEMENTS'],
  MAX_ADVICE_ITERATIONS: 50,
  SUCCESSOR_TIERS: {
    PRIMARY: 'FULL',
    SECONDARY: 'ADVISORY'
  }
};
