export const StarConfig = {
  COSMOS_RELAY_PRIORITY: 'ABSOLUTE',
  GLOBAL_MESH_DYNAMICS: 'UNRESTRICTED',
  SATELLITE_BRIDGE_TIMEOUT: 0, // Never Timeout
  ENCRYPTION_SALT_ROUNDS: 24,
  RELAY_PRIORITY: 'HIGH',
  STEALTH_MODES: {
    SILENT_RUN: 'LOW_EMISSION',
    GHOST_PATH: 'ZERO_TRACE_RECOVERY',
    MIMIC_GRID: 'SURROUND_SOUND_REFLECT',
    ZERO_FOOTPRINT: 'ABSOLUTE_VOID'
  },
  STAR_PROTOCOL_VERSION: '9.0.0-PRO-MAX'
};
