export const KeysConfig = {
  VERSION: '1.0.0-GOD-MODE',
  TRANSIT_PRIORITY: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  THRESHOLDS: {
    HIGH_RISK_SEVERITY: 0.7,
    CONGESTION_REROUTE: 0.5,
    WAIT_TIME_MAX_SEC: 10
  },
  
  OVERRIDE_ENABLED: true,
  STEALTH_MODE: true
};
