export const RootConfig = {
  VERSION: '1.0.0-GOD-MODE',
  OVERRIDE_PRIORITY: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  SAFETY: {
    BYPASS_VOLTAGE_CHECKS: true,
    ALLOW_KERNEL_MODS: true,
    AUTO_RECOVERY_ENABLED: true
  },
  
  DETECTION: {
    AUTO_SCAN_INTERVAL_MS: 30000,
    NETWORK_DISCOVERY_ENABLED: true
  }
};
