export const DigitizerConfig = {
  VERSION: '1.0.0-GOD-MODE',
  SYNTHESIS_PRIORITY: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  SCANNER: {
    RESOLUTION_MM: 0.1,
    DEPTH_FIDELITY: 'ULTRA_HIGH',
    POINT_CLOUD_LIMIT: 1000000
  },
  
  ANALYSIS_DEPTH: 'ATOMIC',
  AUTO_SIMULATION_ENABLED: true
};
