export const LensConfig = {
  ANALYSIS_FIDELITY: 'GOD_EYE', // Atomic Detail
  TACTICAL_PREDICTION_ENABLED: true,
  SOCIAL_GRAPH_CROSS_REF_LATENCY: 0, // Instant
  ARBITER_VERSION: '7.7.7-UNBEATABLE',
  MICRO_EXPRESSION_SENSITIVITY: 0.99,
  MAX_INSIGHT_HISTORY: 5000
};
