export const SentinelConfig = {
  VERSION: '1.0.0-GOD-MODE',
  DEFENSE_PRIORITY: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  SWARM: {
    MIN_UNITS: 4,
    OPTIMAL_UNITS: 12,
    MAX_UNITS: 64,
    SYNC_INTERVAL_MS: 10
  },
  
  BARRIER: {
    DEFAULT_RADIUS_METERS: 2.5,
    MAX_RADIUS_METERS: 10,
    REACTION_TIME_MS: 50
  },
  
  PREDICTION: {
    THREAT_THRESHOLD: 0.85,
    LOOK_AHEAD_MS: 2000
  }
};
