export const VanguardConfig = {
  VERSION: '1.0.0-GOD-MODE',
  DEPLOYMENT_PROTOCOL: 'ULTRA_GOD_PRO_MAX',
  DASHBOARD_REFRESH_MS: 500,
  
  THRESHOLDS: {
    LOW_BATTERY_RTH: 0.2, // Return to Home
    CRITICAL_BATTERY: 0.1,
    SIGNAL_LOSS_TIMEOUT_MS: 3000
  },
  
  AUTONOMOUS_LOS_BYPASS: true,
  DEFENSIVE_ENGAGEMENT_ALLOWED: true,
  CITADEL_SYNC_ENABLED: true
};
