export const BabelConfig = {
  VERSION: '1.0.0-BABEL',
  SNAPSHOT_REDUNDANCY: 4,
  MAX_HISTORY_DEPTH: 1000,
  SYNC_INTERVAL_MS: 600000, // 10 minutes
  VAULT_NODES: ['VAULT_ALPHA', 'VAULT_BETA', 'VAULT_GAMMA']
};
